### PR TITLE
Add option for rate limiting the network requests

### PR DESCRIPTION
**Pull request by galfert**
I took the function from [this gist](https://gist.github.com/mattheworiordan/1084831) but used  Lodash instead of Underscore, because they have per-method packages.

I also simplified the function a bit so it wouldn't need the `_.defer` method.

The rate limit in milliseconds can be added via the `-r` or `--rate-limit` option. Default is 0.

### CODE REVIEW

**Comment by raucao** [comment]
Very cool, thanks!

What do you think about using a default value higher than 0 so that people can't accidentally flood servers with the tool? Or maybe even removing the whole option, so that one doesn't have to think about it.

**Comment by galfert** [comment]
Yes, I thought about having a different default than 0, but couldn't come up with an appropriate value. Might be a good idea to experiment a little bit to see what's reasonable.

I'd like to keep it as a changeable option though. If you are running it against your own personal server, you might want to run it faster because you know that you're the only one hitting that server.

**Comment by raucao** [comment]
> Yes, I thought about having a different default than 0, but couldn't come up with an appropriate value. Might be a good idea to experiment a little bit to see what's reasonable.

Anything higher than 0 is reasonable for almost all servers, so I think we should increase the default before publishing this.

> I'd like to keep it as a changeable option though. If you are running it against your own personal server, you might want to run it faster because you know that you're the only one hitting that server.

Makes sense.

**Comment by galfert** [comment]
How about 250 ms as a start? Still "feels" fast enough but should be sufficient to not flood any server.

**Comment by raucao** [comment]
That's only 4 requests per second. 10 was already too slow for us yesterday. We're talking thousands of documents for kosmos@5apps.com for example. 5apps Storage's per-IP rate limiting is now 25 req/s per IP.

So I would suggest a default rate of at least 25/s.

**Comment by raucao** [comment]
Thanks a lot!

**Pull request merged**
